### ISSUE TITLE
Connecting TableView in Master

### ISSUE THREAD

**Issue by ramon-luis** [uchicago-mobi/MPCS51030-2017-Winter-Forum#101]
I'm having trouble accessing the properties of the prototype cell in the master table view.

I created a controller for the prototype cell, connected the labels to that controller, and then gave the prototype cell an identifier that matched the name of that controller.

Any idea what I'm doing wrong?

I noticed that I'm able to set the Master controller in the storyboard correctly (MasterViewController), but I'm unable to set the controller for the actual tableview to the same controller (MasterViewController).  It appears to be looking for a tableviewController and doesn't recognize the MasterViewController as implementing the required functions.

Is this why I can't access the cell properties?

```
override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cellIdentifier = "SearchResultTableViewCell"
        
        let cell = tableView.dequeueReusableCell(withIdentifier: cellIdentifier, for: indexPath)
        let searchResult = serializedSearchResults[indexPath.row]
        
        cell.titleLabel.text = searchResult.titleURL  // THIS IS AN ERROR
        cell.bodyLabel.text = searchResult.body  // THIS IS AN ERROR
        return cell
    }
```

**Comment by hbennett766** [comment]
Check out the "let cell = " line. You're grabbing the cell by it's identifier, but never casting it as the type of tableViewCell that you've created. The cell is currently of type UITableViewCell instead of your custom cell, and UITableViewCell doesn't have those properties. Try adding "as! NameOfYourCustomTableViewCell", and make sure that you've assigned the prototype cell to be the type of your custom tableViewCell in storyboard.

**Comment by ramon-luis** [comment]
Thank you!  Forgot to cast it!
