### ISSUE TITLE
webview issue

### ISSUE THREAD

**Issue by ramon-luis** [uchicago-mobi/MPCS51030-2017-Winter-Forum#104]
I'm having trouble getting my webview on the detailController to update from the cell on the masterController.  I am passing a URL to a property of the detailController.  The detailController receives this property and makes sure that the webview is not nil, and then calls on the webview to update.  But the webview doesn't update...  I'm printing the webview object and the URL string to the console when .loadRequest is called, so both exist and appear valid (and yet the webview still doesn't load).  I've also added some dummy buttons to test loadRequest on the webview.  The dummy buttons work consistently and almost instantly.  So, for some reason when I pass the info passed from the masterController works erratically and on a delay, if it works at all.

Do I need to delay calling the update the the webview?  I tried using table methods and delegates to pass the data from master to detail and ran into the same issue, which makes me think my problem is with the code in my detailController.  

Any tips or pointers for where I'm going wrong?

Master:
```
override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == "showDetail" {
            if let indexPath = self.tableView.indexPathForSelectedRow {
                let searchResult = serializedSearchResults[indexPath.row]
                let urlToLoad = searchResult.titleURL
                let controller = (segue.destination as! UINavigationController).topViewController as! DetailViewController

                controller.urlToLoad = urlToLoad
                controller.navigationItem.leftBarButtonItem = self.splitViewController?.displayModeButtonItem
                controller.navigationItem.leftItemsSupplementBackButton = true
            }
        }
    }

override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cellIdentifier = "SearchResultTableViewCell"
        
        let cell = tableView.dequeueReusableCell(withIdentifier: cellIdentifier, for: indexPath) as! SearchResultTableViewCell
        
        let searchResult = serializedSearchResults[indexPath.row]
        cell.titleLabel.text = searchResult.titleURL
        cell.bodyLabel.text = searchResult.body
        return cell
    }
```

Detail:
```
class DetailViewController: UIViewController  {
    

    
    var urlToLoad: String? = "http://www.apple.com" {
        didSet {
            print("urlToLoad new value: \(urlToLoad)")
            self.configureView()  // Update the view.
        }
    }

    @IBOutlet weak var urlWebView: UIWebView!
    @IBOutlet weak var bookmarkToolbar: UIToolbar!
    @IBOutlet weak var bookmarksBarButton: UIBarButtonItem!

    @IBAction func cubsButton(_ sender: UIBarButtonItem) {
        let url = "http://www.cubs.com"
        urlWebView.loadRequest(URLRequest(url: URL(string: url)!))
    }
    
    @IBAction func googleButton(_ sender: UIBarButtonItem) {
        let url = "http://www.google.com"
        urlWebView.loadRequest(URLRequest(url: URL(string: url)!))
    }
    
    func configureView() {
        if let urlToLoad = urlToLoad {
            if let urlWebView = urlWebView {
                print("webview loaded, requesting url: \(urlToLoad)")
                urlWebView.loadRequest(URLRequest(url: URL(string: urlToLoad)!))
            }
        }
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        configureView()  // update the view
    }
    
}
```

**Comment by ptnsv** [comment]
Not that it will be helpful to Ramon, but I am seeing the same behavior in my app. I have confirmed with debug prints that the URL and URLRequest are being instantiated correctly, but once I make the UIWebView.loadRequest call, the end result I see is a crash due to "nil while unwrapping an Optional value". It's confusing because right before making the call, I am making sure that those parameters aren't nil.

**Comment by ramon-luis** [comment]
It's likely the webview that is nil, not your URL.

Try using:
```
if let urlToLoad = urlToLoad {
            if let urlWebView = urlWebView {
```

Or

```
 if let urlToLoad = urlToLoad {
                urlWebView?.loadRequest(URLRequest(url: URL(string: urlToLoad)!))
```

But... when I add that check, the webview behavior still doesn't perform well.  So, I'm guessing that I'm still calling the loadRequest in the wrong place or need to use a different method to load the url?  Any help from instructor?

**Comment by susanstevens** [comment]
@ptnsv I think Ramon is correct -- your app is most likely crashing because your web view is nil. Views loaded from storyboard will not be loaded up in `prepareForSegue`. You need to wait for `viewDidLoad` before you access them. The safest thing to do is to check for nil when you access the web view in `configureView`.

@RAM0N-LUIS I'm not sure what's causing your web view to load so slowly when you pass the url string from master to detail. Are you using the same url with your test buttons? It's possible that the url you're setting in `prepareForSegue` is just slower to load...

You might want to use the `UIWebViewDelegate` methods to debug. You can print out when your web view starts and finishes loading content. That way you can see if it's starting to load the url right away and just taking a long time, or if there's something preventing it from starting to load when the detail controller appears.

**Comment by ptnsv** [comment]
@susanstevens That's right, the web view was nil. When the call comes from viewDidLoad, it works alright, so need to wait until then.

Thanks to both of you.

**Comment by jahnagoldman** [comment]
I noticed when you look at the API reference (https://developer.apple.com/reference/uikit/uiwebview  and https://developer.apple.com/reference/webkit/wkwebview) it seems to say to use WKWebView instead of UIWebView in iOS 8 and later - is it ok to use either one then? My app had the issue mentioned above until I tried using the WKWebView, which seemed to work well.

**Comment by hbennett766** [comment]
Good question, posting this as a new issue!
Short answer: either will work
Long answer: #118

**Comment by jahnagoldman** [comment]
Thanks @hbennett766!
