### ISSUE TITLE
Bookmark issues

### ISSUE THREAD

**Issue by lakshman111** [uchicago-mobi/MPCS51030-2017-Winter-Forum#110]
I have two issues with my bookmarks:
1. My favorites won't save after each search (pretty sure it is because I am inserting new favorites into the table in the wrong place, but it doesn't really seem like there is another option).
2. I can't add more than one favorite since they just overwrite each other.

Would a TA mind taking a quick look at my code for me? I just pushed to Github.

**Comment by susanstevens** [comment]
I just took a quick look at your code, and it looks like you're trying to save your favorites to `UserDefaults` inside of your BookmarkViewController. Instead, you should save each favorite to `UserDefaults` when the user taps a "Favorite" button in the DetailViewController. Then, the BookmarkViewController should retrieve the list of favorites from `UserDefaults` and display them in a table view.

You don't need to insert new favorites directly into the table view. You just need to save them to `UserDefaults`. Also, since you will have a list of favorites, you should save them in an array.

**Comment by tabinks** [comment]
thanks @susanstevens
