### ISSUE TITLE
View as option missing devices?

### ISSUE THREAD

**Issue by lakshman111** [uchicago-mobi/MPCS51030-2017-Winter-Forum#19]
I wanted to test out Bull's Eye on my iPhone 6, but I am only able to "View as:" in Main.storyboard for iPhoneSE and iPhone 7, not iPhone 6.  I am able to build for iPhone 6.  I googled around a bit but couldn't find that error as well.  How do I view as for iPhone 6 in the storyboard?

**Comment by hbennett766** [comment]
As far as storyboard is concerned, there's no difference between those devices, because iPhone 6 and 6 plus are exactly the same screen dimensions as the 7 and 7 plus, respectively. You can think of "view as iPhone 7" as "view as iPhone 6 and 7". You can also think of "view as iPhone 7 plus" as "view as iPhone 6 plus and 7 plus."

**Comment by susanstevens** [comment]
Also, the device size you select to view your storyboard doesn't need to match the device you're actually running the app on. Here's a relatively recent [tutorial](http://blog.ionic.io/deploying-to-a-device-without-an-apple-developer-account/) that explains how to get an app running on a device without a paid developer account. (Just ignore all the stuff about Ionic.) Or follow the instructions on page 144 of this week's homework.

**Comment by lakshman111** [comment]
Got it, thanks!
