### ISSUE TITLE
Running warning

### ISSUE THREAD

**Issue by alexliu0809** [uchicago-mobi/MPCS51030-2017-Winter-Forum#22]
Hi, the tutorial uses a web view in a later chapter, and it will cause a running warning: "Class PLBuildVersion is implemented in both...One of the two will be used. Which one is undefined." 

Is it ok that I submitted my homework without removing the web view? 

FYI. Other things are working fine. (i.e. no compile errors/warnings)

**Comment by hbennett766** [comment]
I downloaded your project to check this out, and noticed that you committed assignment 2 to your assignment 1 repository. Before class tomorrow, make sure you accept assignment 2 from the forum and commit your bullseye project to week 2's repository. There will be a new repository for each assignment.

To answer your question, this is a bug on Apple's side. AssetsLibraryServices and PhotoLibraryServices are two frameworks that external developers have no control over. I've been seeing this bug in my own work ever since the iOS 10 release. Don't worry about it, there's nothing you can do! Hopefully Apple will take care of it soon.

https://forums.developer.apple.com/thread/63254

**Comment by alexliu0809** [comment]
Thx.
