### ISSUE TITLE
Adding Buttons programmatically in Swift 3

### ISSUE THREAD

**Issue by ijl0322** [uchicago-mobi/MPCS51030-2017-Winter-Forum#27]
In the slides (adding buttons programmatically), there is a line:

button.addTarget(self, action: #selector(ViewController.buttonAction(_:)), forControlEvents: UIControlEvents,TouchUPInside)

However, when compiling, this gives back the error: Type 'ViewController' has no member 'buttonAction'. I have tried using the following code:

button.addTarget(self, action: #selector(buttonAction), forControlEvents: .touchUpInside)
button.addTarget(self, action: "action:", forControlEvents: UIControlEvents.TouchUpInside)

But most solutions don't seem to work with swift 3. Any suggestions on how to make this work ? 

http://stackoverflow.com/questions/29455107/how-to-create-a-uibutton-programmatically
http://stackoverflow.com/questions/35550966/swift-add-show-action-to-button-programmatically

**Comment by hbennett766** [comment]
A selector is a way to identify a method to execute for an object. In the example you've given, you have a UIButton named "button". You're adding "self" (the button) as a target for the event of touching up inside the button, which means the user lifts their finger off the screen from inside the buttom's frame. The selector identifies the method to perform when the user completes this event. The contents of the selector parentheses is just the name of some method, you can call it whatever you want. In this case, the method is called "buttonAction(_:)". The "ViewController." part is optional, it's just explicitly pointing to class ViewController to find function buttonAction.

Your app is failing to compile because you haven't implemented a function in ViewController.swift called "func buttonAction(_:) { [do something here] }". You can name your function whatever you want, all you have to do is make sure what's inside the selector matches up with it. The case you listed with the selector calling method "buttonAction" would be used if you didn't need to pass any parameters into the function.

The end result is that when a user completes the touch event, the method identified by the selector will be called, and you can do things like open a new page of the app, change the button text, or anything else you want to accomplish.

**Comment by ijl0322** [comment]
I see. I have incorrectly assumed that it is some built in function of ViewController. Thank you!
