### ISSUE TITLE
scrollViewDidEndDecelerating()

### ISSUE THREAD

**Issue by lakshman111** [uchicago-mobi/MPCS51030-2017-Winter-Forum#35]
One of the last project requirements is: "When scrollViewDidEndDecelerating() is called (i.e. scrolling stops), you should automatically update the UILabel with the name of the animal that is showing on the screen. You will need to calculate which “page” is showing using the frame geometry of the scrollview."

After looking through the slides, both the section that deals with the scrollView and the section on geometry, I wasn't able to find a portion that clarifies what "You will need to calculate which 'page' is showing using the frame geometry of the scrollview" means.  Can you link to an example or further clarify the directions?

**Comment by susanstevens** [comment]
If you have pagingEnabled set to true for your scroll view, scrollViewDidEndDecelerating will get called when you land on a new page. You'll want to use a property on UIScrollView called contentOffset to determine which animal is showing and update the label to display the name of that animal.

Let me know if that clarifies things or if you have further questions.

**Comment by tabinks** [comment]
Keeping track of "pages" means that you should track the position of your scrollview in terms of "page" instead of the absolute pixels.  If the width of the screen is 375 and the `contentSize` of the scrollview is sized to represent 3 pages of content, then the content size will be 1,25 (3*375).  Page 1 will be from 0...375, page 2 will be from 376...750, and so on.

Knowing which page you are on will allow you to show the correct label for the animal on a given page.
